   - name: Update Cache
     apt:
      update_cache: yes

   - name: Install docker kubectl kubelet and kubeadm
     apt: name={{ item }} state=latest
     loop: [ 'docker-ce', 'kubelet', 'kubeadm', 'kubectl' ]
  
   - name: Mark hold of updates for kubeadm kubectl and kubelet
     dpkg_selections: name={{ item }} selection=hold
     loop: [ 'docker-ce', 'kubelet', 'kubeadm', 'kubectl' ]

   - name: Add ubuntu user to docker group
     user: name=ubuntu group=docker

   - name: Enable iptables bridge call
     shell: echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
     register: result

   - debug: msg={{ result.stdout }}

   - debug:
      msg: "[Worker] K8S_TOKEN_HOLDER K8S token is {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

   - name: Join master node
     shell: "{{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"
     args:
      warn: no

   - pause:
      seconds: 30