   - name: Update Cache
     apt:
      update_cache: yes

   - name: Install docker kubectl kubelet and kubeadm
     apt: name={{ item }} state=present
     loop: [ 'docker-ce', 'kubelet', 'kubeadm', 'kubectl' ]
     
   - name: Mark hold of updates for kubectl kubeadm and kubelet
     dpkg_selections: name={{ item }} selection=hold 
     loop: [ 'docker-ce', 'kubelet', 'kubeadm', 'kubectl' ]

   - name: Add ubuntu user to docker group
     user: name=ubuntu group=docker

   - name: Enable iptables bridge call
     shell: echo "net.bridge.bridge-nf-call-iptables=1" | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
     register: result

   - debug: msg={{ result.stdout }}

   - name: Initialize the cluster on master node
     shell: kubeadm init --pod-network-cidr=10.244.0.0/16
     register: result

   - debug: msg={{ result.stdout }}

   - name: Create a .kube folder
     file: path=$HOME/.kube state=directory
     become_user: ubuntu

   - name: Copy k8s config files to kube folder
     shell: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
     become_user: ubuntu

   - name: Install weave network
     become: false
     shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

   - pause:
         seconds: 30

   - name: Check the nodes
     shell: kubectl get nodes
     register: nodes
     become: false

   - debug: msg={{ nodes.stdout }}
